### ISSUE TITLE
Ubuntu: exception raised at init

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#120]
Test of 1.6.0 done in Ubuntu 22.04.3 LTS (live system, not installed)
after installation of 1.6.0 deb package TG seems to work fine but it raises exceptions at init.
Seems it cannot find LV2 plugin
```
java.lang.UnsatisfiedLinkError: /opt/tuxguitar/lib/libtuxguitar-synth-lv2-jni.so: liblilv-0.so.0: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2450)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2506)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2705)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2667)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1886)
	at org.herac.tuxguitar.player.impl.midiport.lv2.jni.LV2Object.<clinit>(LV2Object.java:6)
	at org.herac.tuxguitar.player.impl.midiport.lv2.LV2SynthExtension.createExtensions(LV2SynthExtension.java:29)
	at org.herac.tuxguitar.midi.synth.TGSynthExtensionPlugin.connect(TGSynthExtensionPlugin.java:23)
	at org.herac.tuxguitar.util.plugin.TGPluginManager.connectPlugin(TGPluginManager.java:88)
	at org.herac.tuxguitar.util.plugin.TGPluginManager.connectEnabled(TGPluginManager.java:65)
	at org.herac.tuxguitar.app.TuxGuitar.startUIContext(TuxGuitar.java:140)
	at org.herac.tuxguitar.app.TuxGuitar.access$100(TuxGuitar.java:68)
	at org.herac.tuxguitar.app.TuxGuitar$1$1.run(TuxGuitar.java:123)
	at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4857)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4409)
	at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:64)
	at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:116)
	at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:101)
	at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:57)
	at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:45)
	at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35)
```

If someone can test this in a more representative Ubuntu environment this could be interesting.

**Comment by helge17** [comment]
The LV2 plugin needs liblilv-0-0 to be installed. The commit 35625a15b03f553ec2d150a60a2591b2751940b7 adds liblilv-0-0 to the dependencies.

**Comment by guiv42** [comment]
To be honest, I don't understand.
I installed 1.6.0 rpm, and my package manager tells me there *is* a dependency to liblilv-0-0.
If I try to remove this package, package manager tells me it implies removing TuxGuitar 1.6.0 also.
Since the .rpm is derived from the .deb... it puzzles me: how can this dependency be missing?

**Comment by helge17** [comment]
I'm not familiar with rpm and don't currently have an rpm system available, but it seems that rpm or alien has some extra magic to figure out the dependencies of an rpm file and doesn't rely on the dependencies defined in the deb file.

The command (run on my Debian machine)

`$ rpm -qpR tuxguitar-1.6.0_linux-swt.x86_64.rpm`

shows a lot of dependencies (or "capabilities", according to the man page), and one of them is

`liblilv-0.so.0()(64bit)`

I guess I need to take a closer look at the dependencies in the deb files as well.

**Comment by guiv42** [comment]
OK, thanks for your answer.
I should resume one day my attempt to package directly a .rpm in a debian environment... In fact I'm not that far from this objective, it's just a matter of priorities. The download stats show a very small number of downloads for rpm, so it can surely wait.
Note that the naming convention for TG *version* in rpm package is not well interpreted by my package manager. Each time I update my system it asks me to update "obsolete" version `1.6.0_linux-swt - x86_64` and replace it by `1.5.4-5.4 - x86_64`.
A 2-levels versioning convention seems to be needed: `(app version)-(package version) - architecture`

I will close this issue once I have tested it in a Ubuntu environment, so I prefer to wait for next pre-release to get the deb package. No need to hurry for that, it's definitely not urgent

**Comment by guiv42** [comment]
It looks there is also a problem of missing dependency to libfluidsynth (?)
When I open 1.6.0 (installed from rpm package in OpenSUSE Tumbleweed) and try to enable fluidsynth plugin I get the following error:
`/opt/tuxguitar/lib/libtuxguitar-fluidsynth-jni.so: libfluidsynth.so.2: cannot open shared object file: No such file or directory`
I don't have this error when I launch the version I build locally.
Note: I cannot find with my package manager any package providing `libfluidsynth.so.2`, I only find `libfluidsynth.so.3`

**Comment by helge17** [comment]
I added some more dependencies to the deb packages with [b86e32b](https://github.com/helge17/tuxguitar/commit/b86e32b9acdee9f3551a1e088cae0f0e242b9f75).

Currently I am building TuxGuitar for Linux (and Windows) on Debian 11/bullseye that comes with libfluidsynth2. The current Debian 12/bookworm has libfluidsynth3. So I have to upgrade my build system to build TuxGuitar with libfluidsynth3.

**Comment by guiv42** [comment]
Problem of exception at init in Ubuntu environment is solved, so this issue can be closed.
For information: the same problem arises in both Ubuntu 22.04 and OpenSuse Tumbleweed about libfluidsynth3 instead of 2.
I am currently re-opening the option to produce an OpenSuse distribution-compatible rpm package with OpenSuse build service (with the objective to submit 1.6.0). Progressing slowly
