### ISSUE TITLE
Can't make JFX version work on Win10

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#158]
It used to work some time ago, but now with tuxguitar-2023-11-23-snapshot-windows-jfx-x86_64 I get the following error at startup:

```
nov. 26, 2023 11:56:30 AM com.sun.javafx.application.PlatformImpl startup
AVERTISSEMENT: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @388fc646'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Note: "AVERTISSEMENT" in second line means "WARNING", but this warning has been present forever and can be ignored

It is very possible that it's linked to my setup, so I would appreciate if someone can perform the test in another win configuration. My win10 machine is *very* old, and has never been connected to any network. So, definitely obsolete in terms of software. And I'm a bit reluctant to connect it to the Internet for security reasons.
If presence of a bug is confirmed, I could perform a dichotomy to find out when it was introduced.

**Comment by helge17** [comment]
Same problem here.

**Comment by guiv42** [comment]
It looks it's been introduced by 5adbc747977ddecea917785f71877657e5389f69
Should we revert this commit?

**Comment by sugizo** [comment]
**steps**
```
powershell -Command "Remove-Item C:\tuxguitar-*\ -Recurse"
cd %homepath%\Downloads
curl -LC - https://github.com/helge17/tuxguitar/releases/download/2023-11-23-snapshot/tuxguitar-2023-11-23-snapshot-windows-jfx-x86_64.zip -o tuxguitar.zip
powershell -Command "Expand-Archive -LiteralPath %HOMEPATH%\Downloads\tuxguitar.zip -DestinationPath C:\tuxguitar"
powershell -Command "Copy-Item -Path 'C:\tuxguitar\*' -Destination 'C:\' -Recurse"
powershell -Command "Remove-Item C:\tuxguitar -Recurse"
powershell -Command "Remove-Item %HOMEPATH%\Downloads\tuxguitar.zip"
C:\tuxguitar-2023-11-23-snapshot-windows-jfx-x86_64\tuxguitar.exe
```

**result**
not work, no error occured, 
but
tux guitar not opened 

already try double click 
from windows explorer too, 
but 
got the same result

**Comment by helge17** [comment]
> It looks it's been introduced by [5adbc74](https://github.com/helge17/tuxguitar/commit/5adbc747977ddecea917785f71877657e5389f69)
> Should we revert this commit?

The goal of this commit was to be able to use different versions of JFX for different platforms. Since FreeBSD 13.2 ships with JFX 14.0.2.1, I have to use this version, as there is no Maven repo for JFX on FreeBSD. Also for some Linux distributions it may make sense to use the version of SWT and JFX from the operating system, native packages have to use them anyway.

So I would not want to undo the commit as a whole. I will take a look at the problem in the next few days.

**Comment by helge17** [comment]
I don't fully understand all the POM files, but I suspect that after commit 5adbc74 some Linux content has crept into the Windows JFX build. The reason for this could be that I am building the Windows version under Linux: The profile activation in pom.xml selects the Linux profile in this case, even if you build the Windows version. And indeed, the Windows profile didn't even work because of the typo now fixed in commit ceea056297c84b71e7e9c8f45fa34d43a499da54.

So to make sure that the Windows profile is used for the Windows build even if you build on Linux, I added the commit cbd562436a332747cd738199d0190aaeb4c513ed to the build script, which disables the Linux profile and selects the Windows profile manually. Now the JFX (and hopefully all other) builds seem to work.

**Comment by guiv42** [comment]
I don't understand so well these pom files either, however I can confirm that your modifications fixed the issue, thanks.
closed.

**Comment by guiv42** [comment]
@helge17 : could you please check if after this modification the FreeBSD/JFX configuration still works?
On my side it builds, but when I try to run I get a similar error:

```
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
```

**Comment by guiv42** [comment]
OK, thank you.
I need to fix my config then (I'm currently discovering FreeBSD...)
