### ISSUE TITLE
can't open .gp files any more

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#283]
TuxGuitar desktop, SWT, Linux

popup window: `org/apache/commons/io/input/NullInputStream`

Looks like a dependency issue, problem appears with 2f681c7d5c82509fbf6d1ef573ed505070e905ab

edit: *very* annoying... my distro also updated commons-compress to 1.26, so TuxGuitar 1.6.1 installed by the distro's repo does not open .gp files any more.

```
org.herac.tuxguitar.action.TGActionException: org/apache/commons/io/input/NullInputStream
        at org.herac.tuxguitar.app.action.impl.file.TGReadURLAction.processAction(TGReadURLAction.java:35)
        at org.herac.tuxguitar.editor.action.TGActionBase.execute(TGActionBase.java:24)
        at org.herac.tuxguitar.action.TGActionManager.execute(TGActionManager.java:67)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.processOnCurrentThread(TGActionProcessor.java:75)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.processOnCurrentThread(TGActionProcessor.java:88)
        at org.herac.tuxguitar.editor.action.TGActionProcessor$1.run(TGActionProcessor.java:98)
        at org.herac.tuxguitar.thread.TGPooledThreadHandler.processNext(TGPooledThreadHandler.java:66)
        at org.herac.tuxguitar.thread.TGPooledThreadHandler.run(TGPooledThreadHandler.java:86)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.herac.tuxguitar.action.TGActionException: org/apache/commons/io/input/NullInputStream
        at org.herac.tuxguitar.editor.action.file.TGReadSongAction.processAction(TGReadSongAction.java:48)
        at org.herac.tuxguitar.editor.action.TGActionBase.execute(TGActionBase.java:24)
        at org.herac.tuxguitar.action.TGActionManager.execute(TGActionManager.java:67)
        at org.herac.tuxguitar.app.action.impl.file.TGReadURLAction.processAction(TGReadURLAction.java:33)
        ... 8 more
Caused by: org.herac.tuxguitar.io.base.TGFileFormatException: org/apache/commons/io/input/NullInputStream
        at org.herac.tuxguitar.io.gpx.v7.GPXInputStream.read(GPXInputStream.java:28)
        at org.herac.tuxguitar.io.base.TGSongReaderHelper.read(TGSongReaderHelper.java:28)
        at org.herac.tuxguitar.io.base.TGFileFormatManager.read(TGFileFormatManager.java:49)
        at org.herac.tuxguitar.editor.action.file.TGReadSongAction.processAction(TGReadSongAction.java:40)
        ... 11 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/input/NullInputStream
        at org.herac.tuxguitar.io.gpx.v7.GPXFileSystem.getFileContentsAsStream(GPXFileSystem.java:39)
        at org.herac.tuxguitar.io.gpx.v7.GPXInputStream.read(GPXInputStream.java:23)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.input.NullInputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 16 more
```

**Comment by guiv42** [comment]
understood: missing dependency to commons-io

**Comment by thebabush** [comment]
Still seeing this error on Apple Silicon. Tried both release tarballs (2024-03-20-master).

**Comment by thebabush** [comment]
Feel free to ping me to test it out. Also, TuxGuitar being in Java and all, I wonder how difficult it would be to have an Apple Silicon release?

**Comment by helge17** [comment]
pre-release is available now. For MacOS on Apple Silicon search for "arm" in discussion #250.

**Comment by G-eos** [comment]
Opening gp files works well for me on latest version in the repo source.

**Comment by thebabush** [comment]
Same. I tried yesterday and it works. Thanks a lot.

Il giorno 2 apr 2024, alle ore 12:06, G-eos ***@***.***> ha scritto:

﻿

Opening gp files works well for me on latest version in the repo source.

**Comment by guiv42** [comment]
@G-eos , @thebabush : thank you for the feedback. Issue closed.
